server:
  port: 8088
spring:
  application:
    name: MyProject11_1
  datasource:
    url: "jdbc:mysql://localhost:3306/myDataBase3?\
      createDatabaseIfNotExist=true\
      &serverTimezone=Asia/Shanghai\
      &characterEncoding=UTF-8"
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #数据库下划线自动转驼峰
