server:
  port: 8087
spring:
  application:
    name: MyProject10_10
#  redis:
#    host: 127.0.0.1
#    port: 6379
  datasource:
    url: "jdbc:mysql://localhost:3306/myDataBase2?\
      createDatabaseIfNotExist=true\
      &serverTimezone=Asia/Shanghai\
      &characterEncoding=UTF-8"
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
