server:
  port: 8060
spring:
  application:
    name: myProjectRabbitMqConfig
  #配置 rabbitMq 服务器
  rabbitmq:
    # 虚拟主机
    virtual-host: /
    #设置RabbitMQ的IP地址
    host: localhost
    #设置rabbitmq服务器连接端口(应用访问端口号是5672，不是控制台端口号15672)
    port: 5672
    #设置rabbitmq服务器用户名  本地搭建对应的账户密码都是 guest
    username: guest
    #设置rabbitmq服务器密码
    password: guest