server:
  port: 8100
spring:
  application:
    name: myProject_2024_1_10
  datasource:
    url: "jdbc:mysql://localhost:3306/myProject_2024_1_10?\
    createDatabaseIfNotExist=true\
    &serverTimezone=Asia/Shanghai\
    &useUnicode=true\
    &charactorEncoding=UTF-8"
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #数据库下划线自动转驼峰