server:
  port: 8200
spring:
  application:
    name: myProjectSocketLearn
  datasource:
    url: "jdbc:mysql://localhost:3306/myProjectSocketLearn?\
    createDatabaseIfNotExist=true\
    &serverTimezone=Asia/Shanghai\
    &useUnicode=true\
    &charactorEncoding=UTF-8"
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #数据库下划线自动转驼峰

# netty-socketio 配置
socketio:
  host: 127.0.0.1
  port: 8201
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000